.PHONY=test

test:
	go test ./...

vet:
	go vet ./...

staticcheck:
	staticcheck ./...

check:
	go vet ./... && staticcheck ./... && golangci-lint run ./...
# check:
#	go vet ./... && staticcheck ./... && golangci-lint run ./... && govulncheck ./...
