
// Enumerated string type tests.
//
// Automatically generated by `gen-enums.rb`.
package v31

import (
  "testing"
)


// Attack Vector tests
func TestAttackVector(t *testing.T) {
  t.Run("String", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val AttackVector // test value
      exp string // expected string
    } {{ AVNetwork, "NETWORK" }, { AVAdjacentNetwork, "ADJACENT_NETWORK" }, { AVLocal, "LOCAL" }, { AVPhysical, "PHYSICAL" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        got := test.val.String()
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val AttackVector // test value
    } {
      { "invalid", InvalidAttackVector },
      { "garbage", AttackVector(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        got := test.val.String()
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })

  t.Run("UnmarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val string // test value
      exp AttackVector // expected result
    } {{ "NETWORK", AVNetwork }, { "ADJACENT_NETWORK", AVAdjacentNetwork }, { "LOCAL", AVLocal }, { "PHYSICAL", AVPhysical }}

    for _, test := range(passTests) {
      t.Run(test.val, func(t *testing.T) {
        var got AttackVector
        if err := got.UnmarshalText([]byte(test.val)); err != nil {
          t.Fatal(err)
        }

        if got != test.exp {
          t.Fatalf("got %v, exp %v", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val string // test value
    } {
      { "empty", "" },
      { "garbage", "junk" },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        var got AttackVector
        if err := got.UnmarshalText([]byte(test.val)); err == nil {
          t.Fatalf("got %v, exp error", got)
        }
      })
    }
  })

  t.Run("MarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val AttackVector // test value
      exp string // expected string
    } {{ AVNetwork, "NETWORK" }, { AVAdjacentNetwork, "ADJACENT_NETWORK" }, { AVLocal, "LOCAL" }, { AVPhysical, "PHYSICAL" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val AttackVector // test value
    } {
      { "invalid", InvalidAttackVector },
      { "garbage", AttackVector(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })
}
    

// Modified Attack Vector tests
func TestModifiedAttackVector(t *testing.T) {
  t.Run("String", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val ModifiedAttackVector // test value
      exp string // expected string
    } {{ MAVNetwork, "NETWORK" }, { MAVAdjacentNetwork, "ADJACENT_NETWORK" }, { MAVLocal, "LOCAL" }, { MAVPhysical, "PHYSICAL" }, { MAVNotDefined, "NOT_DEFINED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        got := test.val.String()
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val ModifiedAttackVector // test value
    } {
      { "invalid", InvalidModifiedAttackVector },
      { "garbage", ModifiedAttackVector(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        got := test.val.String()
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })

  t.Run("UnmarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val string // test value
      exp ModifiedAttackVector // expected result
    } {{ "NETWORK", MAVNetwork }, { "ADJACENT_NETWORK", MAVAdjacentNetwork }, { "LOCAL", MAVLocal }, { "PHYSICAL", MAVPhysical }, { "NOT_DEFINED", MAVNotDefined }}

    for _, test := range(passTests) {
      t.Run(test.val, func(t *testing.T) {
        var got ModifiedAttackVector
        if err := got.UnmarshalText([]byte(test.val)); err != nil {
          t.Fatal(err)
        }

        if got != test.exp {
          t.Fatalf("got %v, exp %v", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val string // test value
    } {
      { "empty", "" },
      { "garbage", "junk" },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        var got ModifiedAttackVector
        if err := got.UnmarshalText([]byte(test.val)); err == nil {
          t.Fatalf("got %v, exp error", got)
        }
      })
    }
  })

  t.Run("MarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val ModifiedAttackVector // test value
      exp string // expected string
    } {{ MAVNetwork, "NETWORK" }, { MAVAdjacentNetwork, "ADJACENT_NETWORK" }, { MAVLocal, "LOCAL" }, { MAVPhysical, "PHYSICAL" }, { MAVNotDefined, "NOT_DEFINED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val ModifiedAttackVector // test value
    } {
      { "invalid", InvalidModifiedAttackVector },
      { "garbage", ModifiedAttackVector(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })
}
    

// Attack Complexity tests
func TestAttackComplexity(t *testing.T) {
  t.Run("String", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val AttackComplexity // test value
      exp string // expected string
    } {{ ACHigh, "HIGH" }, { ACLow, "LOW" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        got := test.val.String()
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val AttackComplexity // test value
    } {
      { "invalid", InvalidAttackComplexity },
      { "garbage", AttackComplexity(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        got := test.val.String()
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })

  t.Run("UnmarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val string // test value
      exp AttackComplexity // expected result
    } {{ "HIGH", ACHigh }, { "LOW", ACLow }}

    for _, test := range(passTests) {
      t.Run(test.val, func(t *testing.T) {
        var got AttackComplexity
        if err := got.UnmarshalText([]byte(test.val)); err != nil {
          t.Fatal(err)
        }

        if got != test.exp {
          t.Fatalf("got %v, exp %v", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val string // test value
    } {
      { "empty", "" },
      { "garbage", "junk" },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        var got AttackComplexity
        if err := got.UnmarshalText([]byte(test.val)); err == nil {
          t.Fatalf("got %v, exp error", got)
        }
      })
    }
  })

  t.Run("MarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val AttackComplexity // test value
      exp string // expected string
    } {{ ACHigh, "HIGH" }, { ACLow, "LOW" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val AttackComplexity // test value
    } {
      { "invalid", InvalidAttackComplexity },
      { "garbage", AttackComplexity(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })
}
    

// Modified Attack Complexity tests
func TestModifiedAttackComplexity(t *testing.T) {
  t.Run("String", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val ModifiedAttackComplexity // test value
      exp string // expected string
    } {{ MACHigh, "HIGH" }, { MACLow, "LOW" }, { MACNotDefined, "NOT_DEFINED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        got := test.val.String()
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val ModifiedAttackComplexity // test value
    } {
      { "invalid", InvalidModifiedAttackComplexity },
      { "garbage", ModifiedAttackComplexity(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        got := test.val.String()
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })

  t.Run("UnmarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val string // test value
      exp ModifiedAttackComplexity // expected result
    } {{ "HIGH", MACHigh }, { "LOW", MACLow }, { "NOT_DEFINED", MACNotDefined }}

    for _, test := range(passTests) {
      t.Run(test.val, func(t *testing.T) {
        var got ModifiedAttackComplexity
        if err := got.UnmarshalText([]byte(test.val)); err != nil {
          t.Fatal(err)
        }

        if got != test.exp {
          t.Fatalf("got %v, exp %v", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val string // test value
    } {
      { "empty", "" },
      { "garbage", "junk" },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        var got ModifiedAttackComplexity
        if err := got.UnmarshalText([]byte(test.val)); err == nil {
          t.Fatalf("got %v, exp error", got)
        }
      })
    }
  })

  t.Run("MarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val ModifiedAttackComplexity // test value
      exp string // expected string
    } {{ MACHigh, "HIGH" }, { MACLow, "LOW" }, { MACNotDefined, "NOT_DEFINED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val ModifiedAttackComplexity // test value
    } {
      { "invalid", InvalidModifiedAttackComplexity },
      { "garbage", ModifiedAttackComplexity(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })
}
    

// Privileges Required tests
func TestPrivilegesRequired(t *testing.T) {
  t.Run("String", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val PrivilegesRequired // test value
      exp string // expected string
    } {{ PRHigh, "HIGH" }, { PRLow, "LOW" }, { PRNone, "NONE" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        got := test.val.String()
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val PrivilegesRequired // test value
    } {
      { "invalid", InvalidPrivilegesRequired },
      { "garbage", PrivilegesRequired(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        got := test.val.String()
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })

  t.Run("UnmarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val string // test value
      exp PrivilegesRequired // expected result
    } {{ "HIGH", PRHigh }, { "LOW", PRLow }, { "NONE", PRNone }}

    for _, test := range(passTests) {
      t.Run(test.val, func(t *testing.T) {
        var got PrivilegesRequired
        if err := got.UnmarshalText([]byte(test.val)); err != nil {
          t.Fatal(err)
        }

        if got != test.exp {
          t.Fatalf("got %v, exp %v", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val string // test value
    } {
      { "empty", "" },
      { "garbage", "junk" },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        var got PrivilegesRequired
        if err := got.UnmarshalText([]byte(test.val)); err == nil {
          t.Fatalf("got %v, exp error", got)
        }
      })
    }
  })

  t.Run("MarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val PrivilegesRequired // test value
      exp string // expected string
    } {{ PRHigh, "HIGH" }, { PRLow, "LOW" }, { PRNone, "NONE" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val PrivilegesRequired // test value
    } {
      { "invalid", InvalidPrivilegesRequired },
      { "garbage", PrivilegesRequired(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })
}
    

// Modified Privileges Required tests
func TestModifiedPrivilegesRequired(t *testing.T) {
  t.Run("String", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val ModifiedPrivilegesRequired // test value
      exp string // expected string
    } {{ MPRHigh, "HIGH" }, { MPRLow, "LOW" }, { MPRNone, "NONE" }, { MPRNotDefined, "NOT_DEFINED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        got := test.val.String()
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val ModifiedPrivilegesRequired // test value
    } {
      { "invalid", InvalidModifiedPrivilegesRequired },
      { "garbage", ModifiedPrivilegesRequired(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        got := test.val.String()
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })

  t.Run("UnmarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val string // test value
      exp ModifiedPrivilegesRequired // expected result
    } {{ "HIGH", MPRHigh }, { "LOW", MPRLow }, { "NONE", MPRNone }, { "NOT_DEFINED", MPRNotDefined }}

    for _, test := range(passTests) {
      t.Run(test.val, func(t *testing.T) {
        var got ModifiedPrivilegesRequired
        if err := got.UnmarshalText([]byte(test.val)); err != nil {
          t.Fatal(err)
        }

        if got != test.exp {
          t.Fatalf("got %v, exp %v", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val string // test value
    } {
      { "empty", "" },
      { "garbage", "junk" },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        var got ModifiedPrivilegesRequired
        if err := got.UnmarshalText([]byte(test.val)); err == nil {
          t.Fatalf("got %v, exp error", got)
        }
      })
    }
  })

  t.Run("MarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val ModifiedPrivilegesRequired // test value
      exp string // expected string
    } {{ MPRHigh, "HIGH" }, { MPRLow, "LOW" }, { MPRNone, "NONE" }, { MPRNotDefined, "NOT_DEFINED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val ModifiedPrivilegesRequired // test value
    } {
      { "invalid", InvalidModifiedPrivilegesRequired },
      { "garbage", ModifiedPrivilegesRequired(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })
}
    

// User Interaction tests
func TestUserInteraction(t *testing.T) {
  t.Run("String", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val UserInteraction // test value
      exp string // expected string
    } {{ UINone, "NONE" }, { UIRequired, "REQUIRED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        got := test.val.String()
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val UserInteraction // test value
    } {
      { "invalid", InvalidUserInteraction },
      { "garbage", UserInteraction(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        got := test.val.String()
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })

  t.Run("UnmarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val string // test value
      exp UserInteraction // expected result
    } {{ "NONE", UINone }, { "REQUIRED", UIRequired }}

    for _, test := range(passTests) {
      t.Run(test.val, func(t *testing.T) {
        var got UserInteraction
        if err := got.UnmarshalText([]byte(test.val)); err != nil {
          t.Fatal(err)
        }

        if got != test.exp {
          t.Fatalf("got %v, exp %v", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val string // test value
    } {
      { "empty", "" },
      { "garbage", "junk" },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        var got UserInteraction
        if err := got.UnmarshalText([]byte(test.val)); err == nil {
          t.Fatalf("got %v, exp error", got)
        }
      })
    }
  })

  t.Run("MarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val UserInteraction // test value
      exp string // expected string
    } {{ UINone, "NONE" }, { UIRequired, "REQUIRED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val UserInteraction // test value
    } {
      { "invalid", InvalidUserInteraction },
      { "garbage", UserInteraction(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })
}
    

// Modified User Interaction tests
func TestModifiedUserInteraction(t *testing.T) {
  t.Run("String", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val ModifiedUserInteraction // test value
      exp string // expected string
    } {{ MUINone, "NONE" }, { MUIRequired, "REQUIRED" }, { MUINotDefined, "NOT_DEFINED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        got := test.val.String()
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val ModifiedUserInteraction // test value
    } {
      { "invalid", InvalidModifiedUserInteraction },
      { "garbage", ModifiedUserInteraction(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        got := test.val.String()
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })

  t.Run("UnmarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val string // test value
      exp ModifiedUserInteraction // expected result
    } {{ "NONE", MUINone }, { "REQUIRED", MUIRequired }, { "NOT_DEFINED", MUINotDefined }}

    for _, test := range(passTests) {
      t.Run(test.val, func(t *testing.T) {
        var got ModifiedUserInteraction
        if err := got.UnmarshalText([]byte(test.val)); err != nil {
          t.Fatal(err)
        }

        if got != test.exp {
          t.Fatalf("got %v, exp %v", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val string // test value
    } {
      { "empty", "" },
      { "garbage", "junk" },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        var got ModifiedUserInteraction
        if err := got.UnmarshalText([]byte(test.val)); err == nil {
          t.Fatalf("got %v, exp error", got)
        }
      })
    }
  })

  t.Run("MarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val ModifiedUserInteraction // test value
      exp string // expected string
    } {{ MUINone, "NONE" }, { MUIRequired, "REQUIRED" }, { MUINotDefined, "NOT_DEFINED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val ModifiedUserInteraction // test value
    } {
      { "invalid", InvalidModifiedUserInteraction },
      { "garbage", ModifiedUserInteraction(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })
}
    

// Scope tests
func TestScope(t *testing.T) {
  t.Run("String", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val Scope // test value
      exp string // expected string
    } {{ SUnchanged, "UNCHANGED" }, { SChanged, "CHANGED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        got := test.val.String()
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val Scope // test value
    } {
      { "invalid", InvalidScope },
      { "garbage", Scope(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        got := test.val.String()
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })

  t.Run("UnmarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val string // test value
      exp Scope // expected result
    } {{ "UNCHANGED", SUnchanged }, { "CHANGED", SChanged }}

    for _, test := range(passTests) {
      t.Run(test.val, func(t *testing.T) {
        var got Scope
        if err := got.UnmarshalText([]byte(test.val)); err != nil {
          t.Fatal(err)
        }

        if got != test.exp {
          t.Fatalf("got %v, exp %v", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val string // test value
    } {
      { "empty", "" },
      { "garbage", "junk" },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        var got Scope
        if err := got.UnmarshalText([]byte(test.val)); err == nil {
          t.Fatalf("got %v, exp error", got)
        }
      })
    }
  })

  t.Run("MarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val Scope // test value
      exp string // expected string
    } {{ SUnchanged, "UNCHANGED" }, { SChanged, "CHANGED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val Scope // test value
    } {
      { "invalid", InvalidScope },
      { "garbage", Scope(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })
}
    

// Modified Scope tests
func TestModifiedScope(t *testing.T) {
  t.Run("String", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val ModifiedScope // test value
      exp string // expected string
    } {{ MSUnchanged, "UNCHANGED" }, { MSChanged, "CHANGED" }, { MSNotDefined, "NOT_DEFINED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        got := test.val.String()
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val ModifiedScope // test value
    } {
      { "invalid", InvalidModifiedScope },
      { "garbage", ModifiedScope(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        got := test.val.String()
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })

  t.Run("UnmarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val string // test value
      exp ModifiedScope // expected result
    } {{ "UNCHANGED", MSUnchanged }, { "CHANGED", MSChanged }, { "NOT_DEFINED", MSNotDefined }}

    for _, test := range(passTests) {
      t.Run(test.val, func(t *testing.T) {
        var got ModifiedScope
        if err := got.UnmarshalText([]byte(test.val)); err != nil {
          t.Fatal(err)
        }

        if got != test.exp {
          t.Fatalf("got %v, exp %v", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val string // test value
    } {
      { "empty", "" },
      { "garbage", "junk" },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        var got ModifiedScope
        if err := got.UnmarshalText([]byte(test.val)); err == nil {
          t.Fatalf("got %v, exp error", got)
        }
      })
    }
  })

  t.Run("MarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val ModifiedScope // test value
      exp string // expected string
    } {{ MSUnchanged, "UNCHANGED" }, { MSChanged, "CHANGED" }, { MSNotDefined, "NOT_DEFINED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val ModifiedScope // test value
    } {
      { "invalid", InvalidModifiedScope },
      { "garbage", ModifiedScope(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })
}
    

// Cia tests
func TestCia(t *testing.T) {
  t.Run("String", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val Cia // test value
      exp string // expected string
    } {{ CNone, "NONE" }, { CLow, "LOW" }, { CHigh, "HIGH" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        got := test.val.String()
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val Cia // test value
    } {
      { "invalid", InvalidCia },
      { "garbage", Cia(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        got := test.val.String()
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })

  t.Run("UnmarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val string // test value
      exp Cia // expected result
    } {{ "NONE", CNone }, { "LOW", CLow }, { "HIGH", CHigh }}

    for _, test := range(passTests) {
      t.Run(test.val, func(t *testing.T) {
        var got Cia
        if err := got.UnmarshalText([]byte(test.val)); err != nil {
          t.Fatal(err)
        }

        if got != test.exp {
          t.Fatalf("got %v, exp %v", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val string // test value
    } {
      { "empty", "" },
      { "garbage", "junk" },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        var got Cia
        if err := got.UnmarshalText([]byte(test.val)); err == nil {
          t.Fatalf("got %v, exp error", got)
        }
      })
    }
  })

  t.Run("MarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val Cia // test value
      exp string // expected string
    } {{ CNone, "NONE" }, { CLow, "LOW" }, { CHigh, "HIGH" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val Cia // test value
    } {
      { "invalid", InvalidCia },
      { "garbage", Cia(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })
}
    

// Modified Cia tests
func TestModifiedCia(t *testing.T) {
  t.Run("String", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val ModifiedCia // test value
      exp string // expected string
    } {{ MCNone, "NONE" }, { MCLow, "LOW" }, { MCHigh, "HIGH" }, { MCNotDefined, "NOT_DEFINED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        got := test.val.String()
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val ModifiedCia // test value
    } {
      { "invalid", InvalidModifiedCia },
      { "garbage", ModifiedCia(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        got := test.val.String()
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })

  t.Run("UnmarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val string // test value
      exp ModifiedCia // expected result
    } {{ "NONE", MCNone }, { "LOW", MCLow }, { "HIGH", MCHigh }, { "NOT_DEFINED", MCNotDefined }}

    for _, test := range(passTests) {
      t.Run(test.val, func(t *testing.T) {
        var got ModifiedCia
        if err := got.UnmarshalText([]byte(test.val)); err != nil {
          t.Fatal(err)
        }

        if got != test.exp {
          t.Fatalf("got %v, exp %v", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val string // test value
    } {
      { "empty", "" },
      { "garbage", "junk" },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        var got ModifiedCia
        if err := got.UnmarshalText([]byte(test.val)); err == nil {
          t.Fatalf("got %v, exp error", got)
        }
      })
    }
  })

  t.Run("MarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val ModifiedCia // test value
      exp string // expected string
    } {{ MCNone, "NONE" }, { MCLow, "LOW" }, { MCHigh, "HIGH" }, { MCNotDefined, "NOT_DEFINED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val ModifiedCia // test value
    } {
      { "invalid", InvalidModifiedCia },
      { "garbage", ModifiedCia(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })
}
    

// Exploit Code Maturity tests
func TestExploitCodeMaturity(t *testing.T) {
  t.Run("String", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val ExploitCodeMaturity // test value
      exp string // expected string
    } {{ ECMUnproven, "UNPROVEN" }, { ECMProofOfConcept, "PROOF_OF_CONCEPT" }, { ECMFunctional, "FUNCTIONAL" }, { ECMHigh, "HIGH" }, { ECMNotDefined, "NOT_DEFINED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        got := test.val.String()
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val ExploitCodeMaturity // test value
    } {
      { "invalid", InvalidExploitCodeMaturity },
      { "garbage", ExploitCodeMaturity(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        got := test.val.String()
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })

  t.Run("UnmarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val string // test value
      exp ExploitCodeMaturity // expected result
    } {{ "UNPROVEN", ECMUnproven }, { "PROOF_OF_CONCEPT", ECMProofOfConcept }, { "FUNCTIONAL", ECMFunctional }, { "HIGH", ECMHigh }, { "NOT_DEFINED", ECMNotDefined }}

    for _, test := range(passTests) {
      t.Run(test.val, func(t *testing.T) {
        var got ExploitCodeMaturity
        if err := got.UnmarshalText([]byte(test.val)); err != nil {
          t.Fatal(err)
        }

        if got != test.exp {
          t.Fatalf("got %v, exp %v", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val string // test value
    } {
      { "empty", "" },
      { "garbage", "junk" },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        var got ExploitCodeMaturity
        if err := got.UnmarshalText([]byte(test.val)); err == nil {
          t.Fatalf("got %v, exp error", got)
        }
      })
    }
  })

  t.Run("MarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val ExploitCodeMaturity // test value
      exp string // expected string
    } {{ ECMUnproven, "UNPROVEN" }, { ECMProofOfConcept, "PROOF_OF_CONCEPT" }, { ECMFunctional, "FUNCTIONAL" }, { ECMHigh, "HIGH" }, { ECMNotDefined, "NOT_DEFINED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val ExploitCodeMaturity // test value
    } {
      { "invalid", InvalidExploitCodeMaturity },
      { "garbage", ExploitCodeMaturity(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })
}
    

// Remediation Level tests
func TestRemediationLevel(t *testing.T) {
  t.Run("String", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val RemediationLevel // test value
      exp string // expected string
    } {{ RLOfficialFix, "OFFICIAL_FIX" }, { RLTemporaryFix, "TEMPORARY_FIX" }, { RLWorkaround, "WORKAROUND" }, { RLUnavailable, "UNAVAILABLE" }, { RLNotDefined, "NOT_DEFINED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        got := test.val.String()
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val RemediationLevel // test value
    } {
      { "invalid", InvalidRemediationLevel },
      { "garbage", RemediationLevel(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        got := test.val.String()
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })

  t.Run("UnmarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val string // test value
      exp RemediationLevel // expected result
    } {{ "OFFICIAL_FIX", RLOfficialFix }, { "TEMPORARY_FIX", RLTemporaryFix }, { "WORKAROUND", RLWorkaround }, { "UNAVAILABLE", RLUnavailable }, { "NOT_DEFINED", RLNotDefined }}

    for _, test := range(passTests) {
      t.Run(test.val, func(t *testing.T) {
        var got RemediationLevel
        if err := got.UnmarshalText([]byte(test.val)); err != nil {
          t.Fatal(err)
        }

        if got != test.exp {
          t.Fatalf("got %v, exp %v", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val string // test value
    } {
      { "empty", "" },
      { "garbage", "junk" },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        var got RemediationLevel
        if err := got.UnmarshalText([]byte(test.val)); err == nil {
          t.Fatalf("got %v, exp error", got)
        }
      })
    }
  })

  t.Run("MarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val RemediationLevel // test value
      exp string // expected string
    } {{ RLOfficialFix, "OFFICIAL_FIX" }, { RLTemporaryFix, "TEMPORARY_FIX" }, { RLWorkaround, "WORKAROUND" }, { RLUnavailable, "UNAVAILABLE" }, { RLNotDefined, "NOT_DEFINED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val RemediationLevel // test value
    } {
      { "invalid", InvalidRemediationLevel },
      { "garbage", RemediationLevel(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })
}
    

// Confidence tests
func TestConfidence(t *testing.T) {
  t.Run("String", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val Confidence // test value
      exp string // expected string
    } {{ CUnknown, "UNKNOWN" }, { CReasonable, "REASONABLE" }, { CConfirmed, "CONFIRMED" }, { CNotDefined, "NOT_DEFINED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        got := test.val.String()
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val Confidence // test value
    } {
      { "invalid", InvalidConfidence },
      { "garbage", Confidence(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        got := test.val.String()
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })

  t.Run("UnmarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val string // test value
      exp Confidence // expected result
    } {{ "UNKNOWN", CUnknown }, { "REASONABLE", CReasonable }, { "CONFIRMED", CConfirmed }, { "NOT_DEFINED", CNotDefined }}

    for _, test := range(passTests) {
      t.Run(test.val, func(t *testing.T) {
        var got Confidence
        if err := got.UnmarshalText([]byte(test.val)); err != nil {
          t.Fatal(err)
        }

        if got != test.exp {
          t.Fatalf("got %v, exp %v", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val string // test value
    } {
      { "empty", "" },
      { "garbage", "junk" },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        var got Confidence
        if err := got.UnmarshalText([]byte(test.val)); err == nil {
          t.Fatalf("got %v, exp error", got)
        }
      })
    }
  })

  t.Run("MarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val Confidence // test value
      exp string // expected string
    } {{ CUnknown, "UNKNOWN" }, { CReasonable, "REASONABLE" }, { CConfirmed, "CONFIRMED" }, { CNotDefined, "NOT_DEFINED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val Confidence // test value
    } {
      { "invalid", InvalidConfidence },
      { "garbage", Confidence(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })
}
    

// Cia Requirement tests
func TestCiaRequirement(t *testing.T) {
  t.Run("String", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val CiaRequirement // test value
      exp string // expected string
    } {{ CRLow, "LOW" }, { CRMedium, "MEDIUM" }, { CRHigh, "HIGH" }, { CRNotDefined, "NOT_DEFINED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        got := test.val.String()
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val CiaRequirement // test value
    } {
      { "invalid", InvalidCiaRequirement },
      { "garbage", CiaRequirement(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        got := test.val.String()
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })

  t.Run("UnmarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val string // test value
      exp CiaRequirement // expected result
    } {{ "LOW", CRLow }, { "MEDIUM", CRMedium }, { "HIGH", CRHigh }, { "NOT_DEFINED", CRNotDefined }}

    for _, test := range(passTests) {
      t.Run(test.val, func(t *testing.T) {
        var got CiaRequirement
        if err := got.UnmarshalText([]byte(test.val)); err != nil {
          t.Fatal(err)
        }

        if got != test.exp {
          t.Fatalf("got %v, exp %v", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val string // test value
    } {
      { "empty", "" },
      { "garbage", "junk" },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        var got CiaRequirement
        if err := got.UnmarshalText([]byte(test.val)); err == nil {
          t.Fatalf("got %v, exp error", got)
        }
      })
    }
  })

  t.Run("MarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val CiaRequirement // test value
      exp string // expected string
    } {{ CRLow, "LOW" }, { CRMedium, "MEDIUM" }, { CRHigh, "HIGH" }, { CRNotDefined, "NOT_DEFINED" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val CiaRequirement // test value
    } {
      { "invalid", InvalidCiaRequirement },
      { "garbage", CiaRequirement(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })
}
    

// Severity tests
func TestSeverity(t *testing.T) {
  t.Run("String", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val Severity // test value
      exp string // expected string
    } {{ SNone, "NONE" }, { SLow, "LOW" }, { SMedium, "MEDIUM" }, { SHigh, "HIGH" }, { SCritical, "CRITICAL" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        got := test.val.String()
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val Severity // test value
    } {
      { "invalid", InvalidSeverity },
      { "garbage", Severity(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        got := test.val.String()
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })

  t.Run("UnmarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val string // test value
      exp Severity // expected result
    } {{ "NONE", SNone }, { "LOW", SLow }, { "MEDIUM", SMedium }, { "HIGH", SHigh }, { "CRITICAL", SCritical }}

    for _, test := range(passTests) {
      t.Run(test.val, func(t *testing.T) {
        var got Severity
        if err := got.UnmarshalText([]byte(test.val)); err != nil {
          t.Fatal(err)
        }

        if got != test.exp {
          t.Fatalf("got %v, exp %v", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val string // test value
    } {
      { "empty", "" },
      { "garbage", "junk" },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        var got Severity
        if err := got.UnmarshalText([]byte(test.val)); err == nil {
          t.Fatalf("got %v, exp error", got)
        }
      })
    }
  })

  t.Run("MarshalText", func(t *testing.T) {
    // tests expected to pass
    passTests := []struct {
      val Severity // test value
      exp string // expected string
    } {{ SNone, "NONE" }, { SLow, "LOW" }, { SMedium, "MEDIUM" }, { SHigh, "HIGH" }, { SCritical, "CRITICAL" }}

    for _, test := range(passTests) {
      t.Run(test.exp, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != test.exp {
          t.Fatalf("got \"%s\", exp \"%s\"", got, test.exp)
        }
      })
    }

    // tests expected to fail
    failTests := []struct {
      name string // test name
      val Severity // test value
    } {
      { "invalid", InvalidSeverity },
      { "garbage", Severity(255) },
    }

    for _, test := range(failTests) {
      t.Run(test.name, func(t *testing.T) {
        gotBytes, err := test.val.MarshalText()
        if err != nil {
          t.Fatal(err)
        }

        got := string(gotBytes)
        if got != "" {
          t.Fatalf("got \"%s\", exp \"\"", got)
        }
      })
    }
  })
}
    
    