// Enumerated string types.
//
// Automatically generated by `gen-enums.rb`.
package v31

import "fmt"

// Invalid type string error
type InvalidTypeString struct {
  Type, Value string
}

func newInvalidTypeString(typeName, value string) *InvalidTypeString {
  return &InvalidTypeString { typeName, value }
}

func (t InvalidTypeString) Error() string {
  return fmt.Sprintf("invalid %s: \"%s\"", t.Type, t.Value)
}

// packed string of enumeration values
const _pack_ba6499cc006baa2f8f13f074011ebfd1 = `ADJACENT_NETWORKPROOF_OF_CONCEPTTEMPORARY_FIXOFFICIAL_FIXNOT_DEFINEDUNAVAILABLEFUNCTIONALWORKAROUNDREASONABLEUNCHANGEDCONFIRMEDPHYSICALREQUIREDUNPROVENCRITICALUNKNOWNMEDIUMLOCALHIGHNONELOW`


// Attack Vector
type AttackVector uint8

const (
  InvalidAttackVector AttackVector = iota
  AVNetwork
  AVAdjacentNetwork
  AVLocal
  AVPhysical
)

// Parse AttackVector from string.
func ParseAttackVector(s string) (AttackVector, error) {
  switch s {
  case "NETWORK":
    return AVNetwork, nil
  case "ADJACENT_NETWORK":
    return AVAdjacentNetwork, nil
  case "LOCAL":
    return AVLocal, nil
  case "PHYSICAL":
    return AVPhysical, nil
  default:
    return InvalidAttackVector, newInvalidTypeString("AttackVector", s)
  }
}

// Convert AttackVector to string.
func (v AttackVector) String() string {
  switch v {
  case AVNetwork:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[9:16]
  case AVAdjacentNetwork:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[0:16]
  case AVLocal:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[172:177]
  case AVPhysical:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[127:135]
  default:
    return ""
  }
}

// Unmarshal AttackVector from text.
func (v *AttackVector) UnmarshalText(text []byte) error {
  s := string(text)
  switch string(text) {
  case "NETWORK":
    *v = AVNetwork
    return nil
  case "ADJACENT_NETWORK":
    *v = AVAdjacentNetwork
    return nil
  case "LOCAL":
    *v = AVLocal
    return nil
  case "PHYSICAL":
    *v = AVPhysical
    return nil
  default:
    return newInvalidTypeString("AttackVector", s)
  }
}

// Marshal AttackVector to text.
func (v *AttackVector) MarshalText() ([]byte, error) {
  return []byte(v.String()), nil
}


// Modified Attack Vector
type ModifiedAttackVector uint8

const (
  InvalidModifiedAttackVector ModifiedAttackVector = iota
  MAVNetwork
  MAVAdjacentNetwork
  MAVLocal
  MAVPhysical
  MAVNotDefined
)

// Parse ModifiedAttackVector from string.
func ParseModifiedAttackVector(s string) (ModifiedAttackVector, error) {
  switch s {
  case "NETWORK":
    return MAVNetwork, nil
  case "ADJACENT_NETWORK":
    return MAVAdjacentNetwork, nil
  case "LOCAL":
    return MAVLocal, nil
  case "PHYSICAL":
    return MAVPhysical, nil
  case "NOT_DEFINED":
    return MAVNotDefined, nil
  default:
    return InvalidModifiedAttackVector, newInvalidTypeString("ModifiedAttackVector", s)
  }
}

// Convert ModifiedAttackVector to string.
func (v ModifiedAttackVector) String() string {
  switch v {
  case MAVNetwork:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[9:16]
  case MAVAdjacentNetwork:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[0:16]
  case MAVLocal:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[172:177]
  case MAVPhysical:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[127:135]
  case MAVNotDefined:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[57:68]
  default:
    return ""
  }
}

// Unmarshal ModifiedAttackVector from text.
func (v *ModifiedAttackVector) UnmarshalText(text []byte) error {
  s := string(text)
  switch string(text) {
  case "NETWORK":
    *v = MAVNetwork
    return nil
  case "ADJACENT_NETWORK":
    *v = MAVAdjacentNetwork
    return nil
  case "LOCAL":
    *v = MAVLocal
    return nil
  case "PHYSICAL":
    *v = MAVPhysical
    return nil
  case "NOT_DEFINED":
    *v = MAVNotDefined
    return nil
  default:
    return newInvalidTypeString("ModifiedAttackVector", s)
  }
}

// Marshal ModifiedAttackVector to text.
func (v *ModifiedAttackVector) MarshalText() ([]byte, error) {
  return []byte(v.String()), nil
}


// Attack Complexity
type AttackComplexity uint8

const (
  InvalidAttackComplexity AttackComplexity = iota
  ACHigh
  ACLow
)

// Parse AttackComplexity from string.
func ParseAttackComplexity(s string) (AttackComplexity, error) {
  switch s {
  case "HIGH":
    return ACHigh, nil
  case "LOW":
    return ACLow, nil
  default:
    return InvalidAttackComplexity, newInvalidTypeString("AttackComplexity", s)
  }
}

// Convert AttackComplexity to string.
func (v AttackComplexity) String() string {
  switch v {
  case ACHigh:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[177:181]
  case ACLow:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[185:188]
  default:
    return ""
  }
}

// Unmarshal AttackComplexity from text.
func (v *AttackComplexity) UnmarshalText(text []byte) error {
  s := string(text)
  switch string(text) {
  case "HIGH":
    *v = ACHigh
    return nil
  case "LOW":
    *v = ACLow
    return nil
  default:
    return newInvalidTypeString("AttackComplexity", s)
  }
}

// Marshal AttackComplexity to text.
func (v *AttackComplexity) MarshalText() ([]byte, error) {
  return []byte(v.String()), nil
}


// Modified Attack Complexity
type ModifiedAttackComplexity uint8

const (
  InvalidModifiedAttackComplexity ModifiedAttackComplexity = iota
  MACHigh
  MACLow
  MACNotDefined
)

// Parse ModifiedAttackComplexity from string.
func ParseModifiedAttackComplexity(s string) (ModifiedAttackComplexity, error) {
  switch s {
  case "HIGH":
    return MACHigh, nil
  case "LOW":
    return MACLow, nil
  case "NOT_DEFINED":
    return MACNotDefined, nil
  default:
    return InvalidModifiedAttackComplexity, newInvalidTypeString("ModifiedAttackComplexity", s)
  }
}

// Convert ModifiedAttackComplexity to string.
func (v ModifiedAttackComplexity) String() string {
  switch v {
  case MACHigh:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[177:181]
  case MACLow:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[185:188]
  case MACNotDefined:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[57:68]
  default:
    return ""
  }
}

// Unmarshal ModifiedAttackComplexity from text.
func (v *ModifiedAttackComplexity) UnmarshalText(text []byte) error {
  s := string(text)
  switch string(text) {
  case "HIGH":
    *v = MACHigh
    return nil
  case "LOW":
    *v = MACLow
    return nil
  case "NOT_DEFINED":
    *v = MACNotDefined
    return nil
  default:
    return newInvalidTypeString("ModifiedAttackComplexity", s)
  }
}

// Marshal ModifiedAttackComplexity to text.
func (v *ModifiedAttackComplexity) MarshalText() ([]byte, error) {
  return []byte(v.String()), nil
}


// Privileges Required
type PrivilegesRequired uint8

const (
  InvalidPrivilegesRequired PrivilegesRequired = iota
  PRHigh
  PRLow
  PRNone
)

// Parse PrivilegesRequired from string.
func ParsePrivilegesRequired(s string) (PrivilegesRequired, error) {
  switch s {
  case "HIGH":
    return PRHigh, nil
  case "LOW":
    return PRLow, nil
  case "NONE":
    return PRNone, nil
  default:
    return InvalidPrivilegesRequired, newInvalidTypeString("PrivilegesRequired", s)
  }
}

// Convert PrivilegesRequired to string.
func (v PrivilegesRequired) String() string {
  switch v {
  case PRHigh:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[177:181]
  case PRLow:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[185:188]
  case PRNone:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[181:185]
  default:
    return ""
  }
}

// Unmarshal PrivilegesRequired from text.
func (v *PrivilegesRequired) UnmarshalText(text []byte) error {
  s := string(text)
  switch string(text) {
  case "HIGH":
    *v = PRHigh
    return nil
  case "LOW":
    *v = PRLow
    return nil
  case "NONE":
    *v = PRNone
    return nil
  default:
    return newInvalidTypeString("PrivilegesRequired", s)
  }
}

// Marshal PrivilegesRequired to text.
func (v *PrivilegesRequired) MarshalText() ([]byte, error) {
  return []byte(v.String()), nil
}


// Modified Privileges Required
type ModifiedPrivilegesRequired uint8

const (
  InvalidModifiedPrivilegesRequired ModifiedPrivilegesRequired = iota
  MPRHigh
  MPRLow
  MPRNone
  MPRNotDefined
)

// Parse ModifiedPrivilegesRequired from string.
func ParseModifiedPrivilegesRequired(s string) (ModifiedPrivilegesRequired, error) {
  switch s {
  case "HIGH":
    return MPRHigh, nil
  case "LOW":
    return MPRLow, nil
  case "NONE":
    return MPRNone, nil
  case "NOT_DEFINED":
    return MPRNotDefined, nil
  default:
    return InvalidModifiedPrivilegesRequired, newInvalidTypeString("ModifiedPrivilegesRequired", s)
  }
}

// Convert ModifiedPrivilegesRequired to string.
func (v ModifiedPrivilegesRequired) String() string {
  switch v {
  case MPRHigh:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[177:181]
  case MPRLow:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[185:188]
  case MPRNone:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[181:185]
  case MPRNotDefined:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[57:68]
  default:
    return ""
  }
}

// Unmarshal ModifiedPrivilegesRequired from text.
func (v *ModifiedPrivilegesRequired) UnmarshalText(text []byte) error {
  s := string(text)
  switch string(text) {
  case "HIGH":
    *v = MPRHigh
    return nil
  case "LOW":
    *v = MPRLow
    return nil
  case "NONE":
    *v = MPRNone
    return nil
  case "NOT_DEFINED":
    *v = MPRNotDefined
    return nil
  default:
    return newInvalidTypeString("ModifiedPrivilegesRequired", s)
  }
}

// Marshal ModifiedPrivilegesRequired to text.
func (v *ModifiedPrivilegesRequired) MarshalText() ([]byte, error) {
  return []byte(v.String()), nil
}


// User Interaction
type UserInteraction uint8

const (
  InvalidUserInteraction UserInteraction = iota
  UINone
  UIRequired
)

// Parse UserInteraction from string.
func ParseUserInteraction(s string) (UserInteraction, error) {
  switch s {
  case "NONE":
    return UINone, nil
  case "REQUIRED":
    return UIRequired, nil
  default:
    return InvalidUserInteraction, newInvalidTypeString("UserInteraction", s)
  }
}

// Convert UserInteraction to string.
func (v UserInteraction) String() string {
  switch v {
  case UINone:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[181:185]
  case UIRequired:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[135:143]
  default:
    return ""
  }
}

// Unmarshal UserInteraction from text.
func (v *UserInteraction) UnmarshalText(text []byte) error {
  s := string(text)
  switch string(text) {
  case "NONE":
    *v = UINone
    return nil
  case "REQUIRED":
    *v = UIRequired
    return nil
  default:
    return newInvalidTypeString("UserInteraction", s)
  }
}

// Marshal UserInteraction to text.
func (v *UserInteraction) MarshalText() ([]byte, error) {
  return []byte(v.String()), nil
}


// Modified User Interaction
type ModifiedUserInteraction uint8

const (
  InvalidModifiedUserInteraction ModifiedUserInteraction = iota
  MUINone
  MUIRequired
  MUINotDefined
)

// Parse ModifiedUserInteraction from string.
func ParseModifiedUserInteraction(s string) (ModifiedUserInteraction, error) {
  switch s {
  case "NONE":
    return MUINone, nil
  case "REQUIRED":
    return MUIRequired, nil
  case "NOT_DEFINED":
    return MUINotDefined, nil
  default:
    return InvalidModifiedUserInteraction, newInvalidTypeString("ModifiedUserInteraction", s)
  }
}

// Convert ModifiedUserInteraction to string.
func (v ModifiedUserInteraction) String() string {
  switch v {
  case MUINone:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[181:185]
  case MUIRequired:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[135:143]
  case MUINotDefined:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[57:68]
  default:
    return ""
  }
}

// Unmarshal ModifiedUserInteraction from text.
func (v *ModifiedUserInteraction) UnmarshalText(text []byte) error {
  s := string(text)
  switch string(text) {
  case "NONE":
    *v = MUINone
    return nil
  case "REQUIRED":
    *v = MUIRequired
    return nil
  case "NOT_DEFINED":
    *v = MUINotDefined
    return nil
  default:
    return newInvalidTypeString("ModifiedUserInteraction", s)
  }
}

// Marshal ModifiedUserInteraction to text.
func (v *ModifiedUserInteraction) MarshalText() ([]byte, error) {
  return []byte(v.String()), nil
}


// Scope
type Scope uint8

const (
  InvalidScope Scope = iota
  SUnchanged
  SChanged
)

// Parse Scope from string.
func ParseScope(s string) (Scope, error) {
  switch s {
  case "UNCHANGED":
    return SUnchanged, nil
  case "CHANGED":
    return SChanged, nil
  default:
    return InvalidScope, newInvalidTypeString("Scope", s)
  }
}

// Convert Scope to string.
func (v Scope) String() string {
  switch v {
  case SUnchanged:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[109:118]
  case SChanged:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[111:118]
  default:
    return ""
  }
}

// Unmarshal Scope from text.
func (v *Scope) UnmarshalText(text []byte) error {
  s := string(text)
  switch string(text) {
  case "UNCHANGED":
    *v = SUnchanged
    return nil
  case "CHANGED":
    *v = SChanged
    return nil
  default:
    return newInvalidTypeString("Scope", s)
  }
}

// Marshal Scope to text.
func (v *Scope) MarshalText() ([]byte, error) {
  return []byte(v.String()), nil
}


// Modified Scope
type ModifiedScope uint8

const (
  InvalidModifiedScope ModifiedScope = iota
  MSUnchanged
  MSChanged
  MSNotDefined
)

// Parse ModifiedScope from string.
func ParseModifiedScope(s string) (ModifiedScope, error) {
  switch s {
  case "UNCHANGED":
    return MSUnchanged, nil
  case "CHANGED":
    return MSChanged, nil
  case "NOT_DEFINED":
    return MSNotDefined, nil
  default:
    return InvalidModifiedScope, newInvalidTypeString("ModifiedScope", s)
  }
}

// Convert ModifiedScope to string.
func (v ModifiedScope) String() string {
  switch v {
  case MSUnchanged:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[109:118]
  case MSChanged:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[111:118]
  case MSNotDefined:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[57:68]
  default:
    return ""
  }
}

// Unmarshal ModifiedScope from text.
func (v *ModifiedScope) UnmarshalText(text []byte) error {
  s := string(text)
  switch string(text) {
  case "UNCHANGED":
    *v = MSUnchanged
    return nil
  case "CHANGED":
    *v = MSChanged
    return nil
  case "NOT_DEFINED":
    *v = MSNotDefined
    return nil
  default:
    return newInvalidTypeString("ModifiedScope", s)
  }
}

// Marshal ModifiedScope to text.
func (v *ModifiedScope) MarshalText() ([]byte, error) {
  return []byte(v.String()), nil
}


// Cia
type Cia uint8

const (
  InvalidCia Cia = iota
  CNone
  CLow
  CHigh
)

// Parse Cia from string.
func ParseCia(s string) (Cia, error) {
  switch s {
  case "NONE":
    return CNone, nil
  case "LOW":
    return CLow, nil
  case "HIGH":
    return CHigh, nil
  default:
    return InvalidCia, newInvalidTypeString("Cia", s)
  }
}

// Convert Cia to string.
func (v Cia) String() string {
  switch v {
  case CNone:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[181:185]
  case CLow:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[185:188]
  case CHigh:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[177:181]
  default:
    return ""
  }
}

// Unmarshal Cia from text.
func (v *Cia) UnmarshalText(text []byte) error {
  s := string(text)
  switch string(text) {
  case "NONE":
    *v = CNone
    return nil
  case "LOW":
    *v = CLow
    return nil
  case "HIGH":
    *v = CHigh
    return nil
  default:
    return newInvalidTypeString("Cia", s)
  }
}

// Marshal Cia to text.
func (v *Cia) MarshalText() ([]byte, error) {
  return []byte(v.String()), nil
}


// Modified Cia
type ModifiedCia uint8

const (
  InvalidModifiedCia ModifiedCia = iota
  MCNone
  MCLow
  MCHigh
  MCNotDefined
)

// Parse ModifiedCia from string.
func ParseModifiedCia(s string) (ModifiedCia, error) {
  switch s {
  case "NONE":
    return MCNone, nil
  case "LOW":
    return MCLow, nil
  case "HIGH":
    return MCHigh, nil
  case "NOT_DEFINED":
    return MCNotDefined, nil
  default:
    return InvalidModifiedCia, newInvalidTypeString("ModifiedCia", s)
  }
}

// Convert ModifiedCia to string.
func (v ModifiedCia) String() string {
  switch v {
  case MCNone:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[181:185]
  case MCLow:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[185:188]
  case MCHigh:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[177:181]
  case MCNotDefined:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[57:68]
  default:
    return ""
  }
}

// Unmarshal ModifiedCia from text.
func (v *ModifiedCia) UnmarshalText(text []byte) error {
  s := string(text)
  switch string(text) {
  case "NONE":
    *v = MCNone
    return nil
  case "LOW":
    *v = MCLow
    return nil
  case "HIGH":
    *v = MCHigh
    return nil
  case "NOT_DEFINED":
    *v = MCNotDefined
    return nil
  default:
    return newInvalidTypeString("ModifiedCia", s)
  }
}

// Marshal ModifiedCia to text.
func (v *ModifiedCia) MarshalText() ([]byte, error) {
  return []byte(v.String()), nil
}


// Exploit Code Maturity
type ExploitCodeMaturity uint8

const (
  InvalidExploitCodeMaturity ExploitCodeMaturity = iota
  ECMUnproven
  ECMProofOfConcept
  ECMFunctional
  ECMHigh
  ECMNotDefined
)

// Parse ExploitCodeMaturity from string.
func ParseExploitCodeMaturity(s string) (ExploitCodeMaturity, error) {
  switch s {
  case "UNPROVEN":
    return ECMUnproven, nil
  case "PROOF_OF_CONCEPT":
    return ECMProofOfConcept, nil
  case "FUNCTIONAL":
    return ECMFunctional, nil
  case "HIGH":
    return ECMHigh, nil
  case "NOT_DEFINED":
    return ECMNotDefined, nil
  default:
    return InvalidExploitCodeMaturity, newInvalidTypeString("ExploitCodeMaturity", s)
  }
}

// Convert ExploitCodeMaturity to string.
func (v ExploitCodeMaturity) String() string {
  switch v {
  case ECMUnproven:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[143:151]
  case ECMProofOfConcept:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[16:32]
  case ECMFunctional:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[79:89]
  case ECMHigh:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[177:181]
  case ECMNotDefined:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[57:68]
  default:
    return ""
  }
}

// Unmarshal ExploitCodeMaturity from text.
func (v *ExploitCodeMaturity) UnmarshalText(text []byte) error {
  s := string(text)
  switch string(text) {
  case "UNPROVEN":
    *v = ECMUnproven
    return nil
  case "PROOF_OF_CONCEPT":
    *v = ECMProofOfConcept
    return nil
  case "FUNCTIONAL":
    *v = ECMFunctional
    return nil
  case "HIGH":
    *v = ECMHigh
    return nil
  case "NOT_DEFINED":
    *v = ECMNotDefined
    return nil
  default:
    return newInvalidTypeString("ExploitCodeMaturity", s)
  }
}

// Marshal ExploitCodeMaturity to text.
func (v *ExploitCodeMaturity) MarshalText() ([]byte, error) {
  return []byte(v.String()), nil
}


// Remediation Level
type RemediationLevel uint8

const (
  InvalidRemediationLevel RemediationLevel = iota
  RLOfficialFix
  RLTemporaryFix
  RLWorkaround
  RLUnavailable
  RLNotDefined
)

// Parse RemediationLevel from string.
func ParseRemediationLevel(s string) (RemediationLevel, error) {
  switch s {
  case "OFFICIAL_FIX":
    return RLOfficialFix, nil
  case "TEMPORARY_FIX":
    return RLTemporaryFix, nil
  case "WORKAROUND":
    return RLWorkaround, nil
  case "UNAVAILABLE":
    return RLUnavailable, nil
  case "NOT_DEFINED":
    return RLNotDefined, nil
  default:
    return InvalidRemediationLevel, newInvalidTypeString("RemediationLevel", s)
  }
}

// Convert RemediationLevel to string.
func (v RemediationLevel) String() string {
  switch v {
  case RLOfficialFix:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[45:57]
  case RLTemporaryFix:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[32:45]
  case RLWorkaround:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[89:99]
  case RLUnavailable:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[68:79]
  case RLNotDefined:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[57:68]
  default:
    return ""
  }
}

// Unmarshal RemediationLevel from text.
func (v *RemediationLevel) UnmarshalText(text []byte) error {
  s := string(text)
  switch string(text) {
  case "OFFICIAL_FIX":
    *v = RLOfficialFix
    return nil
  case "TEMPORARY_FIX":
    *v = RLTemporaryFix
    return nil
  case "WORKAROUND":
    *v = RLWorkaround
    return nil
  case "UNAVAILABLE":
    *v = RLUnavailable
    return nil
  case "NOT_DEFINED":
    *v = RLNotDefined
    return nil
  default:
    return newInvalidTypeString("RemediationLevel", s)
  }
}

// Marshal RemediationLevel to text.
func (v *RemediationLevel) MarshalText() ([]byte, error) {
  return []byte(v.String()), nil
}


// Confidence
type Confidence uint8

const (
  InvalidConfidence Confidence = iota
  CUnknown
  CReasonable
  CConfirmed
  CNotDefined
)

// Parse Confidence from string.
func ParseConfidence(s string) (Confidence, error) {
  switch s {
  case "UNKNOWN":
    return CUnknown, nil
  case "REASONABLE":
    return CReasonable, nil
  case "CONFIRMED":
    return CConfirmed, nil
  case "NOT_DEFINED":
    return CNotDefined, nil
  default:
    return InvalidConfidence, newInvalidTypeString("Confidence", s)
  }
}

// Convert Confidence to string.
func (v Confidence) String() string {
  switch v {
  case CUnknown:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[159:166]
  case CReasonable:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[99:109]
  case CConfirmed:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[118:127]
  case CNotDefined:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[57:68]
  default:
    return ""
  }
}

// Unmarshal Confidence from text.
func (v *Confidence) UnmarshalText(text []byte) error {
  s := string(text)
  switch string(text) {
  case "UNKNOWN":
    *v = CUnknown
    return nil
  case "REASONABLE":
    *v = CReasonable
    return nil
  case "CONFIRMED":
    *v = CConfirmed
    return nil
  case "NOT_DEFINED":
    *v = CNotDefined
    return nil
  default:
    return newInvalidTypeString("Confidence", s)
  }
}

// Marshal Confidence to text.
func (v *Confidence) MarshalText() ([]byte, error) {
  return []byte(v.String()), nil
}


// Cia Requirement
type CiaRequirement uint8

const (
  InvalidCiaRequirement CiaRequirement = iota
  CRLow
  CRMedium
  CRHigh
  CRNotDefined
)

// Parse CiaRequirement from string.
func ParseCiaRequirement(s string) (CiaRequirement, error) {
  switch s {
  case "LOW":
    return CRLow, nil
  case "MEDIUM":
    return CRMedium, nil
  case "HIGH":
    return CRHigh, nil
  case "NOT_DEFINED":
    return CRNotDefined, nil
  default:
    return InvalidCiaRequirement, newInvalidTypeString("CiaRequirement", s)
  }
}

// Convert CiaRequirement to string.
func (v CiaRequirement) String() string {
  switch v {
  case CRLow:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[185:188]
  case CRMedium:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[166:172]
  case CRHigh:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[177:181]
  case CRNotDefined:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[57:68]
  default:
    return ""
  }
}

// Unmarshal CiaRequirement from text.
func (v *CiaRequirement) UnmarshalText(text []byte) error {
  s := string(text)
  switch string(text) {
  case "LOW":
    *v = CRLow
    return nil
  case "MEDIUM":
    *v = CRMedium
    return nil
  case "HIGH":
    *v = CRHigh
    return nil
  case "NOT_DEFINED":
    *v = CRNotDefined
    return nil
  default:
    return newInvalidTypeString("CiaRequirement", s)
  }
}

// Marshal CiaRequirement to text.
func (v *CiaRequirement) MarshalText() ([]byte, error) {
  return []byte(v.String()), nil
}


// Severity
type Severity uint8

const (
  InvalidSeverity Severity = iota
  SNone
  SLow
  SMedium
  SHigh
  SCritical
)

// Parse Severity from string.
func ParseSeverity(s string) (Severity, error) {
  switch s {
  case "NONE":
    return SNone, nil
  case "LOW":
    return SLow, nil
  case "MEDIUM":
    return SMedium, nil
  case "HIGH":
    return SHigh, nil
  case "CRITICAL":
    return SCritical, nil
  default:
    return InvalidSeverity, newInvalidTypeString("Severity", s)
  }
}

// Convert Severity to string.
func (v Severity) String() string {
  switch v {
  case SNone:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[181:185]
  case SLow:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[185:188]
  case SMedium:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[166:172]
  case SHigh:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[177:181]
  case SCritical:
    return _pack_ba6499cc006baa2f8f13f074011ebfd1[151:159]
  default:
    return ""
  }
}

// Unmarshal Severity from text.
func (v *Severity) UnmarshalText(text []byte) error {
  s := string(text)
  switch string(text) {
  case "NONE":
    *v = SNone
    return nil
  case "LOW":
    *v = SLow
    return nil
  case "MEDIUM":
    *v = SMedium
    return nil
  case "HIGH":
    *v = SHigh
    return nil
  case "CRITICAL":
    *v = SCritical
    return nil
  default:
    return newInvalidTypeString("Severity", s)
  }
}

// Marshal Severity to text.
func (v *Severity) MarshalText() ([]byte, error) {
  return []byte(v.String()), nil
}

